### ISSUE TITLE
USER STORY: Landing page

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#1]
As a **Site User** I can **view information on the site immediately** so that **I can know what the purpose of the site is**

**Acceptance Criteria**
- Landing page complete with info and images

**Tasks**
- [x] Task 1: Create base.html & index.html template
- [x] Task 2: Add HTML and CSS to index.html
- [x] Task 3: Add Images to cloudinary
