### ISSUE TITLE
USER STORY: Login/Logout

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#10]
As a **registered user** I can **login and logout of the site** so that **I can access the site content**

**Acceptance Criteria**
- User can login and logout of the site
- User is redirected to the home page after they log in

**Tasks**
- [x] Task 1: Wire up login/logout links 
- [x] Task 2: Redirect to home page after login 
- [x] Task 3: Install and customise allauth account templates
