### ISSUE TITLE
USER STORY: Selectable Categories

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#12]
As a **Site User** I can **choose the category of project I want to see** so that **I can easily filter posts to find posts that are suited to my needs**

**Acceptance Criteria**
- Specific projects will appear depending on the category assigned to the project post and selected by the user

**Tasks**
- [x] Task 1: Add category fields to models
- [x] Task 2: Add option to select category in add post template
- [x] Task 3: Add category pages to filter posts based on selected category
