### ISSUE TITLE
USER STORY: Create Drafts

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#14]
As a **Site User** I can **create draft posts** so that **I can finish writing and adding content**

**Acceptance Criteria**
- Users can create own project post without publishing them
- Users can access drafted posts in their user profile
- Users can read/update/delete unpublished posts

**Tasks**
- [ ] Task 1: Add a status to the project model
- [ ] Task 2: Publish the project post if the status is set to published
- [ ] Task 3: Add link in profile page to view/edit/delete drafts
