### ISSUE TITLE
USER STORY: Create Drafts

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#15]
As a **Site Admin** I can **create draft posts** so that **I can finish writing and adding content later**

**Acceptance Criteria**
- Admin can add a project post in admin panel
- Admin can select draft/published option with draft set to default

**Tasks**
- [x] Task 1: Create model for project post
- [x] Task 2: Create superuser/admin to log in to admin panel
- [x] Task 3: Add project post model to admin panel
- [x] Task 4: Add summernote editor
