### ISSUE TITLE
USER STORY: View profile

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#19]
As a **Site User** I can **view my own profile** so that **I can see my own details and projects**

**Acceptance Criteria**
- Each user can see their own individual profile
- Each user can see their own posts

**Tasks**
- [ ] Task 1: Create user profile template template
- [ ] Task 2: Set up view
- [ ] Task 3: wire up url
