### ISSUE TITLE
USER STORY: View Projects Page

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#2]
As a **Site User** I can **view the different projects on the site** so that **I can see what I would like to find out more about**

**Acceptance Criteria**
- All projects appear as cards on the projects page

**Tasks**
- [x] Task 1: Add view code for projects page
- [x] Task 2: Add content to template
- [x] Task 3: Wire up url
