### ISSUE TITLE
USER STORY: Set up profile Image and bio

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#21]
As a **Site User** I can **set a bio and profile pic** so that **I can customise my own profile**

**Acceptance Criteria**
- Users can see enter a bio and upload a profile picture

**Tasks**
- [ ] Task 1: Create model for profile
- [ ] Task 2: Set up view
- [ ] Task 3: wire up url
