### ISSUE TITLE
USER STORY: Open a post

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#5]
As a **Site User** I can **click on a post** so that **I can read the full text**

**Acceptance Criteria**
- Each project can be opened up on its own page to reveal more information about it

**Tasks**
- [x] Task 1: Make post cards clickable
- [x] Task 2: Redirect each post to a specific detailed project page
- [x] Task 3: Structure & style detailed page
