### ISSUE TITLE
USER STORY: Comment on a post

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#6]
As a **Site User** I can **leave comments on a post** so that **I can be give my opinion and be involved in the conversation**

**Acceptance Criteria**
- If the user is logged in, they can leave a comment on a post

**Tasks**
- [x] Task 1: Create comment model
- [x] Task 2: Create comment view
- [x] Task 3: Add comment section in project detail view
