### ISSUE TITLE
USER STORY: Like / Unlike

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#8]
As a **Site User** I can **like or unlike a post** so that **I can interact with the content**

**Acceptance Criteria**
- If the user is logged in, they can click a button add a like to the post

**Tasks**
- [x] Task 1: Create like button
- [x] Task 2: Add view for liking or un-liking a project post
- [x] Task 3: Change style of like button based on if the post is liked or not
