### ISSUE TITLE
USER STORY: Register an Account

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/craftmasters#9]
As a **Site User** I can **register an account** so that **I can access the full range of features on the site**

**Acceptance Criteria**
- User can register an account with the site
- User details are visible in the admin panel

**Tasks**
- [x] Task 1: Install allauth
- [x] Task 2: Update requirements, urls
- [x] Task 3: Add to settings
